# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$os$shell$character$directory"""
right_format = """$all"""

[character] # The name of the module we are configuring is 'character'
vimcmd_symbol = '[](green)'
vimcmd_replace_one_symbol = '[](purple)'
vimcmd_replace_symbol = '[](purple)'
vimcmd_visual_symbol = '[](yellow)'
success_symbol = '[➜](bold green) ' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red) '

[directory.substitutions]
'~/Sites' = 'S'
'~/WebApps' = 'WA'
'~/WebDev' = 'WD'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) ) '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
modified = '!${count}'
untracked = '?${count}'

[shell]
disabled = false
fish_indicator = '[󰈺 ](blue)'

[os.symbols]
Fedora = '[ ](blue)'
Manjaro = '[ ](green)'
Ubuntu = '[󰕈 ](red)'

[os]
disabled = false

[bun]
symbol = ' '

[deno]
symbol = ' '

[php]
symbol = ' '

[sudo]
disabled = false
symbol = ' '
style = 'red'
