gui:
  language: 'en'
  theme:
    activeBorderColor:
      - '#74c7ec'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: '#313244'
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: '#74c7ec'
